>#  HW1. 나만의 numpy bible 만들기
학번: A70064, 이름: 안종민

In [ ]:
import numpy as np

배열 기본

In [ ]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1) # a1 어레이를 출력 : [ 1 2 3 4 5 ]
print(type(a1)) # 어레이 a1의 type : numpy.ndarray
print(a1.shape) # 엘리먼트 1개가 있는 튜플 쉐잎(1차원이라 , 뒤에 없음) (5, )
print(a1.ndim) # 몇 차원인지 반환 1
print(a1.dtype) # 데이터타입을 반환
print(a1.size) # 어레이 길이(크기) 반환
print(a1.itemsize) # 몇 바이트인지 반환 // int64 -> 64비트 -> 8바이트

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1
int64
5
8


In [ ]:
a2 = np.array([[1, 2, 3] , [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(a2)
print(a2.shape)
print(a2[0, 0], a2[1, 2], a2[2, 2]) # 넘파이 어레이의 인덱싱 방식은 조금 다름!! 주의!!
print(a2.ndim) # 2
print(a2.dtype) # int64
print(a2.size) # 12
print(a2.itemsize) # int64 -> 64비트 -> 8바이트


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
1 6 9
2
int64
12
8


2. 특정 배열 생성

In [ ]:
print(np.zeros(10))
print(np.ones(10))
print(np.ones((3, 3)))
print(np.full((3, 3), 3.14))
print(np.eye(3)) # 단위행렬 identity mat...
print(np.tri(3))
print(np.empty(10)) # 어떤 값이 들어갈지 보장할 수 없음, garbage값이 들어감, 빨리 만들고 싶을 때 사용
print(a1)
print(np.zeros_like(a1)) # a1하고 같은 쉐잎으로 0을 채워서 만듬
print(np.ones_like(a1)) # a1하고 같은 쉐잎으로 1을 채워서 만듬
print(np.arange(0, 30, 2)) # 0부터 30까지 2스텝으로 만들어라
print(np.linspace(0, 1, 5)) # 0부터 1까지 5개로 나눠라
print(np.logspace(1, 5, 20)) # log scale 형태로 20개 생성
x = a1.astype(np. int32) # a1의 타입을 바꿔서 x로 반환 // a1은 바뀌지 않음
print(x)
print(x.dtype)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[3.14 3.14 3.14]
 [3.14 3.14 3.14]
 [3.14 3.14 3.14]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 2 3 4 5]
[0 0 0 0 0]
[1 1 1 1 1]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]
[0.   0.25 0.5  0.75 1.  ]
[1.00000000e+01 1.62377674e+01 2.63665090e+01 4.28133240e+01
 6.95192796e+01 1.12883789e+02 1.83298071e+02 2.97635144e+02
 4.83293024e+02 7.84759970e+02 1.27427499e+03 2.06913808e+03
 3.35981829e+03 5.45559478e+03 8.85866790e+03 1.43844989e+04
 2.33572147e+04 3.79269019e+04 6.15848211e+04 1.00000000e+05]
[1 2 3 4 5]
int32


랜덤 생성

In [ ]:
print(np.random.random((3, 3))) # 3x3 크기로 [0.0 1.0) 실수값 생성 (균등분포)
print(np.random.rand(3, 3)) # 3x3 크기로 [0.0 1.0) 실수값 생성 (균등분포)
print(np.random.randint(0, 10, (3, 3))) # 0 ~ 10-1 까지 3x3 크기 정수로 생성
print(np.random.normal(0, 1, (3, 3))) # 평균 0과 표준편차1로된 정규 분포로 생성 3x3 크기로 생성 // 평균과 표준편차를 직접 설정
print(np.random.randn(3, 3)) # 표준정규분포 생성 (평균: 0, 표준편차: 1 고정) // 표준정규분포로 자동 생성

[[0.72516076 0.17243062 0.11471992]
 [0.25007724 0.80515031 0.43035355]
 [0.12846141 0.79844043 0.54991973]]
[[0.931131   0.93784219 0.85734265]
 [0.05578382 0.81242249 0.83623736]
 [0.57186094 0.42937216 0.38918408]]
[[5 1 3]
 [1 2 2]
 [4 4 7]]
[[ 0.33390786  0.71691794 -1.89539733]
 [-1.3392608  -1.18294257 -0.02219058]
 [-0.6730071   0.0979061   2.07768645]]
[[-0.30522706 -2.75483549  1.59314396]
 [ 0.00748305  0.01812795 -0.81137583]
 [-0.33547029 -0.14015247  0.40511849]]


배열 수정

In [ ]:
print(a2)
print(a2.T) # 전치 행렬 //transpose mat
print(a2.swapaxes(0, 1)) # 0번축과 1번축을 바꿔라 -> 전치 행렬과 같은 표현
print(a1)
a1 = np.insert(a1, 5, 10) # 5번 인덱스에 10을 추가해라
print(a1)
print(a1.reshape(2, 3)) # a1이 직접 바뀌는게 아님. 그냥 a1을 수정한것을 반환만 하는거임
a1.resize(3, 2) # a1이 직접 바뀜 (a1을 직접 수정해서 a1에 다시 저장됨)
print(a1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
[1 2 3 4 5]
[ 1  2  3  4  5 10]
[[ 1  2  3]
 [ 4  5 10]]
[[ 1  2]
 [ 3  4]
 [ 5 10]]


배열 인덱싱

In [ ]:
a3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
               [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
               [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print('----------') # [start : stop : step]
print(a3)
print(a3[2, 2, 2])
print(a3[1, 1, -1])
print('----------')
print(a2)
print(a2[1, 1:])
print(a2[:2, :2])
print(a2[1:, ::-1])
print(a2[::-1, ::-1])
print('----------')
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
bi = [True, False, True, False, True]
print(a1[bi]) # boolean indexing
fi = [0 ,2]
print(a1[fi]) # fancy indexing // 0번 인덱스와 2번인덱스만 선택하겠따.
print('----------')

----------
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
9
6
----------
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[5 6]
[[1 2]
 [4 5]]
[[ 6  5  4]
 [ 9  8  7]
 [12 11 10]]
[[12 11 10]
 [ 9  8  7]
 [ 6  5  4]
 [ 3  2  1]]
----------
[1 2 3 4 5]
[1 3 5]
[1 3]
----------


배열 원소 삭제

In [ ]:
print(a1)
b1 = np.delete(a1, 1) # 1번 인덱스 원소를 삭제하고 b1에 반환해라 -> a1은 바뀌지 않음
print('----------')
print(a1)
print(b1)
print('----------')
print(a2)
b1 = np.delete(a2, 1, axis = 0) # 0번축(행)에서 1번 인덱스 삭제해라
print('----------')
print(b1)

[1 2 3 4 5]
----------
[1 2 3 4 5]
[1 3 4 5]
----------
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
----------
[[ 1  2  3]
 [ 7  8  9]
 [10 11 12]]


복사

In [ ]:
a = np.array([1, 2, 3, 4]) #list 슬라이싱은 복사의 개념
b = a[1:3] # 1번 인덱스부터 3번 인덱스 직전까지 인덱싱 // numpy의 슬라이싱은 원본의 한 부분
print(b)
b[0] = 9
print(b)
print(a) # b를 수정했는데 a가 수정되어버렸음

[2 3]
[9 3]
[1 9 3 4]


In [ ]:
a = np.array([1, 2, 3, 4])
b = a[1:3].copy() # 이렇게 copy떠서 b에 저장하면 a(원본)이 수정되지 않음
print(b)
b[0] = 9
print(b)
print(a)

[2 3]
[9 3]
[1 2 3 4]


베열 수정2

In [ ]:
a2 = np.arange(1, 10).reshape(3, 3) # 1차원 배열을 2차원으로 수정
print(a2)
b2 = np.arange(11, 20).reshape(3, 3)
print(b2)
print('----------')
c2 = np.append(a2, b2)
print(c2)
print('----------')
c2 = np.append(a2, b2, axis=0) # 0번축(행)으로 이어 붙인다.
print(c2)
print('----------')
c2 = np.append(a2, b2, axis=1) # 1번축(열)로 이어 붙인다.
print(c2)
print('----------')
print(np.vstack([a2, b2])) # 0번축(행)으로 이어 붙인다.
print(np.hstack([a2, b2])) # 1번축(열)로 이어 붙인다.

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
----------
[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
----------
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
----------
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
----------
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


In [ ]:
print(a1)

[1 2 3 4 5]


In [ ]:
b1, c1 = np.split(a1, [2]) # a1의 2번 인덱스 위치에서 쪼갠다
print(a1)
print('----------')
print(b1, c1)
print('----------')
print(a2)
print('----------')
b2, c2 = np.vsplit(a2, [2])
print(b2)
print('----------')
print(c2) # 쪼개도 차원이 바뀌지 않음
print(c2.ndim)
print('----------')
b2, c2 = np.hsplit(a2, [2])
print(b2)
print('----------')
print(c2) # 쪼개도 차원이 바뀌지 않음
print(c2.ndim)


[1 2 3 4 5]
----------
[1 2] [3 4 5]
----------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------
[[1 2 3]
 [4 5 6]]
----------
[[7 8 9]]
2
----------
[[1 2]
 [4 5]
 [7 8]]
----------
[[3]
 [6]
 [9]]
2


broadcasting

In [ ]:
a = np.array([1, 2, 3])
b = 2 # -> [2, 2, 2]로 확장된 후에(브로드캐스팅) 곱해지는거임
print(a * b)

[2 4 6]


In [ ]:
a = np.array([[0, 0, 0],
              [10, 10, 10],
              [20, 20, 20],
              [30, 30, 30]])
b = np.array([1, 2, 3]) # [1, 2, 3]이 브로드캐스팅되어 더해짐
print(a + b)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


In [ ]:
a = np.array([0, 10, 20, 30]).reshape(4, 1)
print(a)
b = np.array([1, 2, 3])
print(a + b) # a는 행이 커지고, b는 열이 커져서 서로 모양이 같게 4x3로 맞춰서 연산

[[ 0]
 [10]
 [20]
 [30]]
[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


산술

In [ ]:
a1 = np.array([1, 2, 3])
print(a1)
print(np.add(a1, 1)) # +1
print(np.subtract(a1, 1)) # -1
print(np.negative(a1)) # * -1
print(np.multiply(a1, 2)) # * 2
print(np.divide(a1, 2)) # 2로 나누기
print(np.mod(a1, 2)) # 2로 나눈 나머지
print(np.floor_divide(a1, 2)) # 2로 나눈 몫
print(np.power(a1, 2)) # 제곱
print(np.sqrt(a1)) # 제곱근

[1 2 3]
[2 3 4]
[0 1 2]
[-1 -2 -3]
[2 4 6]
[0.5 1.  1.5]
[1 0 1]
[0 1 1]
[1 4 9]
[1.         1.41421356 1.73205081]


절대값

In [ ]:
a1 = np.array([1, -2, -3, -4])
print(np.absolute(a1))
print(np.abs(a1))

[1 2 3 4]
[1 2 3 4]


지수로그

In [ ]:
a1 = np.array([1, 2, 3, 4])
print(np.square(a1)) # 제곱
print(np.power(a1, 3)) # 세제곱
print(np.exp(a1)) # 상수e의 거듭제곱
print(np.exp2(a1)) # 2의 거듭제곱
print(np.log(a1))
print(np.log2(a1))
print(np.log10(a1))

[ 1  4  9 16]
[ 1  8 27 64]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[ 2.  4.  8. 16.]
[0.         0.69314718 1.09861229 1.38629436]
[0.        1.        1.5849625 2.       ]
[0.         0.30103    0.47712125 0.60205999]


삼각함수

In [ ]:
t = np.deg2rad(45) # 각도에서 라디안
print(t)
print(np.rad2deg(t))

a1 = np.array([0, 1, 2, 3, t]) # t는 현재 라디안
print(np.sin(a1))
print(np.cos(a1))
print(np.tan(a1))

0.7853981633974483
45.0
[0.         0.84147098 0.90929743 0.14112001 0.70710678]
[ 1.          0.54030231 -0.41614684 -0.9899925   0.70710678]
[ 0.          1.55740772 -2.18503986 -0.14254654  1.        ]


집계함수

In [ ]:
a1 = np.array([[1, 2], [3, 4]])
print(a1)
print(a1.sum(), np.sum(a1)) # 둘 다 같음. 원소의 합
print(a1.sum(axis=0), np.sum(a1, axis=0)) # 0번축(행)으로 합
print(a1.sum(axis=1), np.sum(a1, axis=1)) # 0번축(행)으로 합
print(np.cumsum(a1)) # 누적합
print(np.cumsum(a1, axis=0)) # 누적합
print(np.cumsum(a1, axis=1)) # 누적합

[[1 2]
 [3 4]]
10 10
[4 6] [4 6]
[3 7] [3 7]
[ 1  3  6 10]
[[1 2]
 [4 6]]
[[1 3]
 [3 7]]


In [ ]:
a1 = np.array([[1, 3, 10], [5, 12, 6], [7, 5, 100]])
print(a1)
print(np.diff(a1)) # 차분 계산 // 차분 계산은 디폴트가 -1(마지막축)인 1번축(열)로 계산됨
print(np.prod(a1)) # 원소끼리 모두 곱
print(np.cumprod(a1)) # 원소 누적 곱
b1 = np.ones_like(a2)
print(b1)
print(a2)
print(np.dot(a2, b1)) # 행렬곱
print(np.matmul(a2, b1)) # 행렬곱

[[  1   3  10]
 [  5  12   6]
 [  7   5 100]]
[[ 2  7]
 [ 7 -6]
 [-2 95]]
37800000
[       1        3       30      150     1800    10800    75600   378000
 37800000]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 6  6  6]
 [15 15 15]
 [24 24 24]]
[[ 6  6  6]
 [15 15 15]
 [24 24 24]]


In [ ]:
a1 = np.array([[1, 2, 3], [5, 12, 6], [7, 5, 100]])
print(a1)
print(np.mean(a1)) # 평균  // axis 지원
print(np.var(a1)) # 분산 // axis 지원
print(np.min(a1))
print(np.max(a1))
print(np.median(a1)) # 중간값


[[  1   2   3]
 [  5  12   6]
 [  7   5 100]]
15.666666666666666
898.2222222222222
1
100
5.0


In [ ]:
a1 = np.array([[False, True, True], [False, True, False], [False, False, True]])
print(a1)

[[False  True  True]
 [False  True False]
 [False False  True]]


In [ ]:
print(np.any(a1)) # or의 개념 // 하나라도 true이면 true
print(np.any(a1, axis=0)) # or의 개념
print(np.all(a1)) # and의 개념 // 모두 true여야 true
print(np.all(a1, axis=0)) # and의 개념

True
[False  True  True]
False
[False False False]


비교

In [ ]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
print(a1 == 2)
print(a1 != 2)
print(a1 < 2)
print(a1 > 2)
print(a1 <= 2)
print(a1 >= 2)

[1 2 3 4 5]
[False  True False False False]
[ True False  True  True  True]
[ True False False False False]
[False False  True  True  True]
[ True  True False False False]
[False  True  True  True  True]


boolean

In [ ]:
a1 = np.arange(1, 10).reshape(3, 3)
print(a1)
print(a1 > 2)
print(a1 < 7)
print(a1 < 7)
print(a1 <= 7)
print(a1 >= 7)
print(a1 == 7)
print(a1 != 7)
print('--------------')
print((a1 > 2) & (a1 < 7)) # and
print(a1[(a1 > 2) & (a1 < 7)]) # boolean 인덱싱 // 중요!!!!!!!!!!!!!!!!!
print((a1 > 2) | (a1 < 7)) # or
print(a1[(a1 > 2) | (a1 < 7)]) # boolean 인덱싱 // 중요!!!!!!!!!!!!!!!!!
print((a1 > 2) ^ (a1 < 7)) # xor
print(a1[(a1 > 2) ^ (a1 < 7)]) # boolean 인덱싱 // 중요!!!!!!!!!!!!!!!!!
print(~(a1 > 2)) # not
print(a1[~(a1 > 2)]) # boolean 인덱싱 // 중요!!!!!!!!!!!!!!!!!

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [False False False]]
[[ True  True  True]
 [ True  True  True]
 [False False False]]
[[ True  True  True]
 [ True  True  True]
 [ True False False]]
[[False False False]
 [False False False]
 [ True  True  True]]
[[False False False]
 [False False False]
 [ True False False]]
[[ True  True  True]
 [ True  True  True]
 [False  True  True]]
--------------
[[False False  True]
 [ True  True  True]
 [False False False]]
[3 4 5 6]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[1 2 3 4 5 6 7 8 9]
[[ True  True False]
 [False False False]
 [ True  True  True]]
[1 2 7 8 9]
[[ True  True False]
 [False False False]
 [False False False]]
[1 2]


정렬

In [ ]:
a1 = np.random.randint(1, 10, size = 10)
print(a1)
print(np.sort(a1)) # a1 안바꾸고 반환만함
print(np.argsort(a1)) # 정렬을 위한 인덱스 반환
print(a1.sort()) # 반환하는게 아니라 a1을 정렬하여 바꿈
print(a1)

[5 1 3 8 9 2 6 9 5 6]
[1 2 3 5 5 6 6 8 9 9]
[1 5 2 0 8 6 9 3 7 4]
None
[1 2 3 5 5 6 6 8 9 9]


입출력

In [ ]:
a1 = np.random.randint(1, 10, size = 10)
b1 = np.random.randint(1, 10, size = 10)
print(a1)
print(b1)
np.save('a', a1) # 파일로 저장함
np.savez('ab', x = a1, y = b1) # 여러 파일로 저장함
!ls

[1 2 7 6 2 4 4 2 4 4]
[5 2 2 9 4 5 5 9 6 5]
'6장 numpy 기본.pdf'   a.csv  'efile_download.acl?FILE_SEQ=FMPUJOOMEPMVW'
 ab.npz		       a.npy   sample_data


In [ ]:
a2 = np.load('a.npy')
print(a2)
ab2 = np.load('ab.npz') # 딕셔너리 형태로 저장됨
print(ab2)
print(ab2.files) # Key가 출력도힘
print(ab2['x']) # Key를 통해 확인
print(ab2['y']) # Key를 통해 확인

[1 2 7 6 2 4 4 2 4 4]
NpzFile 'ab.npz' with keys: x, y
['x', 'y']
[1 2 7 6 2 4 4 2 4 4]
[5 2 2 9 4 5 5 9 6 5]


In [ ]:
print(a2)
np.savetxt('a.csv', a2, delimiter=',')
!cat a.csv
csv = np.loadtxt('a.csv', delimiter=',')
print(csv)

[1 2 7 6 2 4 4 2 4 4]
1.000000000000000000e+00
2.000000000000000000e+00
7.000000000000000000e+00
6.000000000000000000e+00
2.000000000000000000e+00
4.000000000000000000e+00
4.000000000000000000e+00
2.000000000000000000e+00
4.000000000000000000e+00
4.000000000000000000e+00
[1. 2. 7. 6. 2. 4. 4. 2. 4. 4.]
