>#  HW1. 나만의 pandas bible 만들기
학번: A70064, 이름: 안종민

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# 시리즈 만드는 법!
s = pd.Series([0, 1, 1.5, 2, 3.2])
print(s)
print(type(s))
print(s.name)
print(s.dtype)
print(s.shape)
print(s.ndim)
print(s.size)
s

0    0.0
1    1.0
2    1.5
3    2.0
4    3.2
dtype: float64
<class 'pandas.core.series.Series'>
None
float64
(5,)
1
5


0    0.0
1    1.0
2    1.5
3    2.0
4    3.2
dtype: float64

In [ ]:
print(s.values) # .values는 series 에 있는 값들만 모아서 numpy array로 반환해줌
print(type(s.values))
print(s.index)
print(s[1])
print(type(s[1]))
print(s[1:5]) # 인덱스 1부터 4까지
print(type(s[1:5])) # 시리즈를 슬라이싱하면 시리즈
print(s>6) # 단일값 6이 브로드캐스팅돼서 각 원소끼리 비교 후 boolean을 가진 시리즈로 반환

[0.  1.  1.5 2.  3.2]
<class 'numpy.ndarray'>
RangeIndex(start=0, stop=5, step=1)
1.0
<class 'numpy.float64'>
1    1.0
2    1.5
3    2.0
4    3.2
dtype: float64
<class 'pandas.core.series.Series'>
0    False
1    False
2    False
3    False
4    False
dtype: bool


In [ ]:
#시리즈 만드는 법 2
s = pd.Series([0, 1, 1.5, 2, 3.2], index= ['a', 'b', 'c', 'd', 'e']) # 인덱스 또는 레이블이라고 함
print(s)

a    0.0
b    1.0
c    1.5
d    2.0
e    3.2
dtype: float64


In [ ]:
print(s['c'])
print(s[1:2]) # 'a', 'b' ... 로 인덱싱해도 정수 인덱싱도 사용할 수 있음
print(s['b':'e']) # 레이블로 슬라이싱하면 e전까지가 아니라 e까지 포함해서 슬라이싱됨 // 정수 인덱싱은 end-1까지 슬라이싱.

print(s[['c', 'b', 'a']]) # 바깥 대괄호는 인덱싱하기 위한 괄호, 안쪽 대괄호는 '리스트' 표현하는 대괄호
print('b' in s) # s에 b레이블이 있는가? -> boolean 반환

1.5
b    1.0
dtype: float64
b    1.0
c    1.5
d    2.0
e    3.2
dtype: float64
c    1.5
b    1.0
a    0.0
dtype: float64
True


In [ ]:
s = pd.Series([0, 1, 1.5, 2, 3.2, 2, 1.5], index= [2, 4, 6, 8, 10, 12, 14])
s

2     0.0
4     1.0
6     1.5
8     2.0
10    3.2
12    2.0
14    1.5
dtype: float64

In [ ]:
print(s[2]) # 레이블이 정수인 경우 레이블 인덱싱이 사용됨
# print[s[1]] # 내가 정의한 레이블이 정수인 경우 정의한 정수만 인덱스로 사용 가능 <- 에러 발생
print(s[2:4]) # 슬라이싱할때는 자동 부여된 정수 인덱싱 사용
print(s.unique()) # 중복되는건 제외한 array가 반환 // 많이 사용됨
print(s.isin([0.25, 1.5])) # 0.25 또는 1.5가 s에 있으면 true // boolean 시리즈로 반환

0.0
6    1.5
8    2.0
dtype: float64
[0.  1.  1.5 2.  3.2]
2     False
4     False
6      True
8     False
10    False
12    False
14     True
dtype: bool


In [ ]:
print(s.value_counts()) # 엘리멘트의 갯수를 카운트해서 시리즈로 반환
s1 = s.value_counts()
print(s1.values)
print(s1.index)

1.5    2
2.0    2
0.0    1
1.0    1
3.2    1
Name: count, dtype: int64
[2 2 1 1 1]
Index([1.5, 2.0, 0.0, 1.0, 3.2], dtype='float64')


In [ ]:
# 시리즈 만드는 법 3 (파이썬의 딕셔너리 -> 시리즈로 만듦)
fruit = {'사과' :846, '배' :343, '바나나' :17, '딸기' :2954, '오렌지' :440} # 딕셔너리 생성
fruit_s = pd.Series(fruit) # 딕셔너리 fruit를 시리즈로 변환
fruit_s

사과      846
배       343
바나나      17
딸기     2954
오렌지     440
dtype: int64

In [ ]:
fruit_s['배']
fruit_s['배':'딸기']

배       343
바나나      17
딸기     2954
dtype: int64

In [ ]:
# dataframe 만드는 법 1
pd.DataFrame([{'A':2, 'B':4, 'D':3}, {'A':4, 'B':5, 'C':7}]) # key가 column index가 됨

A  B    D    C
0  2  4  3.0  NaN
1  4  5  NaN  7.0

In [ ]:
# dataframe 만드는 법 2
pd.DataFrame(np.random.rand(5,5),
             columns=['a', 'b', 'c', 'd', 'e'],
             index=[1, 2, 3, 4, 5])

a         b         c         d         e
1  0.266739  0.079018  0.363675  0.005319  0.667884
2  0.219565  0.919093  0.732558  0.040448  0.152800
3  0.714789  0.163847  0.346280  0.206410  0.427950
4  0.440355  0.152417  0.252058  0.997581  0.465842
5  0.632476  0.875128  0.562777  0.256779  0.834641

In [ ]:
fruit_fresh = {'사과' :846, '배' :343, '바나나' :17, '딸기' :2954, '오렌지' :440}
fresh_s = pd.Series(fruit_fresh)
fresh_s

사과      846
배       343
바나나      17
딸기     2954
오렌지     440
dtype: int64

In [ ]:
fruit_rotten = {'사과' :23, '배' :12, '바나나' :1, '딸기' :498, '오렌지' :54}
rotten_s = pd.Series(fruit_rotten)
rotten_s

사과      23
배       12
바나나      1
딸기     498
오렌지     54
dtype: int64

In [ ]:
# dataframe 만드는 법 3 (딕셔너리로 만든 각각의 두 시리즈를 하나의 데이터 프레임으로 변환)
fruit_df = pd.DataFrame({'fresh':fresh_s, 'rotten':rotten_s})
fruit_df

fresh  rotten
사과     846      23
배      343      12
바나나     17       1
딸기    2954     498
오렌지    440      54

In [ ]:
# fruit_df['all fruit'] = fruit_df['fresh'] + fruit_df['rotten']
fruit_df['all fruit'] = np.sum(fruit_df, axis=1) # column 축(column끼리 합) 합 -> 사과 fresh + 사과 rotten = 모든 사과
fruit_df

fresh  rotten  all fruit
사과     846      23        869
배      343      12        355
바나나     17       1         18
딸기    2954     498       3452
오렌지    440      54        494

In [ ]:
print(fruit_df.index)
#print(fruit_df.columns)
#print(fruit_df.values)
#print(fruit_df.dtypes)
#print(fruit_df.shape)
#print(fruit_df.ndim)
#print(fruit_df.size)

#print(fruit_df['all fruit'])
#print(fruit_df['fresh'])
#print(fruit_df['rotten'])

print(fruit_df['fresh']['바나나']) # 컬럼 인덱싱 -> 로우 인덱싱
print(fruit_df['바나나':'딸기']) # 슬라이싱은 레이블 인덱싱 // 컬럼 인덱싱은 에러남. 사용할 수 없음

print(fruit_df[['fresh', 'all fruit']]) # 여러 컬럼 선택 -> 리스트!

Index(['사과', '배', '바나나', '딸기', '오렌지'], dtype='object')
17
     fresh  rotten  all fruit
바나나     17       1         18
딸기    2954     498       3452
     fresh  all fruit
사과     846        869
배      343        355
바나나     17         18
딸기    2954       3452
오렌지    440        494


In [ ]:
print(fruit_df['all fruit'])
print(type(fruit_df['all fruit']))
fruit_df = fruit_df.div(fruit_df['all fruit'], axis=0)
print(fruit_df)

사과      869
배       355
바나나      18
딸기     3452
오렌지     494
Name: all fruit, dtype: int64
<class 'pandas.core.series.Series'>
        fresh    rotten  all fruit
사과   0.973533  0.026467        1.0
배    0.966197  0.033803        1.0
바나나  0.944444  0.055556        1.0
딸기   0.855736  0.144264        1.0
오렌지  0.890688  0.109312        1.0


In [ ]:
idx1 = pd.Index([2, 4, 6, 8, 10])
idx2 = pd.Index([1, 3, 5, 7, 9])
print(idx1.append(idx2)) # idx1가 바뀌지 않고, 반환하는 것임
print(idx1)
print(idx2)

print(idx1.difference(idx2)) # 차이
print(idx1.intersection(idx2)) # 교집합
print(idx1.symmetric_difference(idx2))
print(idx1.delete(0))  # 0번 인덱스 삭제

Index([2, 4, 6, 8, 10, 1, 3, 5, 7, 9], dtype='int64')
Index([2, 4, 6, 8, 10], dtype='int64')
Index([1, 3, 5, 7, 9], dtype='int64')
Index([2, 4, 6, 8, 10], dtype='int64')
Index([], dtype='int64')
Index([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int64')
Index([4, 6, 8, 10], dtype='int64')


Series indexing

In [ ]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd', 'e'])
print(s.keys())
print(list(s.items()))
print('------------')
print(s)
print(s[2])
print(s['b':'c'])
print('------------')
print(s)
print(s[1:3])
print(s[s>1.2]&[s<3.0])
print('------------')

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
[('a', 0.0), ('b', 0.25), ('c', 0.5), ('d', 0.75), ('e', 1.0)]
------------
a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64
0.5
b    0.25
c    0.50
dtype: float64
------------
a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64
b    0.25
c    0.50
dtype: float64
Series([], dtype: bool)
------------


<ipython-input-144-28768a1b4963>:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[2])
<ipython-input-144-28768a1b4963>:11: FutureWarning: Logical ops (and, or, xor) between Pandas objects and dtype-less sequences (e.g. list, tuple) are deprecated and will raise in a future version. Wrap the object in a Series, Index, or np.array before operating instead.
  print(s[s>1.2]&[s<3.0])


In [ ]:
s = pd.Series(['a', 'b', 'c', 'd', 'e'], index= [1, 3, 5, 7, 9])
print(s)
print('--------------')
print(s[1]) # label-based indexing(slicing), explicit
print('--------------')
print(s[1:3]) # integer-location based (indexing, slicing)
print('--------------')
print(s.iloc[1]) # integer-location based indexing
print('--------------')
print(s.iloc[1:3]) # integer-location based slicing
print('--------------')
print(s.loc[1]) # label-based indexing
print('--------------')
print(s.loc[1:3]) # label-based slicing

1    a
3    b
5    c
7    d
9    e
dtype: object
--------------
a
--------------
3    b
5    c
dtype: object
--------------
b
--------------
3    b
5    c
dtype: object
--------------
a
--------------
1    a
3    b
dtype: object


DataFrame indexing

In [ ]:
fruit_fresh = {'사과' : 846, '배' : 343, '바나나': 17, '딸기' : 2954, '오렌지': 440}
fresh_s = pd.Series(fruit_fresh)
fruit_rotten = {'사과' : 232, '배' : 123, '바나나': 45, '딸기' : 2, '오렌지': 30}
rotten_s = pd.Series(fruit_rotten)
fruit_df = pd.DataFrame({'fresh':fresh_s, 'rotten':rotten_s})
fruit_df['모든과일'] = np.sum(fruit_df, axis=1)
fruit_df

fresh  rotten  모든과일
사과     846     232  1078
배      343     123   466
바나나     17      45    62
딸기    2954       2  2956
오렌지    440      30   470

In [ ]:
print(fruit_df['모든과일'])
print(fruit_df.모든과일)
print()
print(fruit_df.values)
print(type(fruit_df.values))
print(fruit_df.values[0])

사과     1078
배       466
바나나      62
딸기     2956
오렌지     470
Name: 모든과일, dtype: int64
사과     1078
배       466
바나나      62
딸기     2956
오렌지     470
Name: 모든과일, dtype: int64

[[ 846  232 1078]
 [ 343  123  466]
 [  17   45   62]
 [2954    2 2956]
 [ 440   30  470]]
<class 'numpy.ndarray'>
[ 846  232 1078]


df의 column indexing (중요)

In [ ]:
print(fruit_df)

     fresh  rotten  모든과일
사과     846     232  1078
배      343     123   466
바나나     17      45    62
딸기    2954       2  2956
오렌지    440      30   470


In [ ]:
print(fruit_df['fresh']) # 컬럼 인덱싱
print(fruit_df['fresh']['바나나']) # 컬럼 로우 인덱싱
print(fruit_df['사과':'딸기']) # 로우 슬라이싱
# print(fruit_df[0]) # dataframe은 integer indexing 불가
# print(fruit_df['fresh':]) # column slicing 불가
# print(fruit_df['딸기']) # 불가

사과      846
배       343
바나나      17
딸기     2954
오렌지     440
Name: fresh, dtype: int64
17
     fresh  rotten  모든과일
사과     846     232  1078
배      343     123   466
바나나     17      45    62
딸기    2954       2  2956


In [ ]:
print(fruit_df.loc['바나나']) # 레이블 인덱싱 (행 인덱싱)
print(fruit_df.loc['바나나', 'rotten']) # 레이블 인덱싱 (행, 열)
print('------------')
print(fruit_df.iloc[2]) # Integer indexing (row 방향)
print(fruit_df.iloc[2,1]) # Integer indexing (헹, 열)
print(fruit_df.iloc[:3]) #   Integer indexing (헹, 열)
print(fruit_df.iloc[:3, :2]) # Integer indexing (헹, 열)

fresh     17
rotten    45
모든과일      62
Name: 바나나, dtype: int64
45
------------
fresh     17
rotten    45
모든과일      62
Name: 바나나, dtype: int64
45
     fresh  rotten  모든과일
사과     846     232  1078
배      343     123   466
바나나     17      45    62
     fresh  rotten
사과     846     232
배      343     123
바나나     17      45


Boolean indexing

In [ ]:
print(fruit_df['rotten'] > 100)
print('-----')

print(fruit_df.loc[fruit_df['rotten'] > 10]) # boolean indexing
print(fruit_df.loc[[True, False, False, True, False]])

사과      True
배       True
바나나    False
딸기     False
오렌지    False
Name: rotten, dtype: bool
-----
     fresh  rotten  모든과일
사과     846     232  1078
배      343     123   466
바나나     17      45    62
오렌지    440      30   470
    fresh  rotten  모든과일
사과    846     232  1078
딸기   2954       2  2956


In [ ]:
print(fruit_df.loc[(fruit_df['fresh'] > 300) & fruit_df['rotten'] < 5])
print()

     fresh  rotten  모든과일
사과     846     232  1078
배      343     123   466
바나나     17      45    62
딸기    2954       2  2956
오렌지    440      30   470



In [ ]:
print(fruit_df.drop(fruit_df.loc[fruit_df['rotten']>100].index))
# print(fruit_df.drop(fruit_df.loc[fruit_df['rotten']>100].index, axis=1))
print(fruit_df.drop(fruit_df.loc[fruit_df['rotten']>100].index))
print(fruit_df.drop(fruit_df.loc[fruit_df['rotten']>100].index))

     fresh  rotten  모든과일
바나나     17      45    62
딸기    2954       2  2956
오렌지    440      30   470
     fresh  rotten  모든과일
바나나     17      45    62
딸기    2954       2  2956
오렌지    440      30   470
     fresh  rotten  모든과일
바나나     17      45    62
딸기    2954       2  2956
오렌지    440      30   470


In [ ]:
print(fruit_df.loc['바나나']>40)
print(type(fruit_df.loc['바나나']>40))
print(fruit_df)
print('--------')
print(fruit_df[[False, True, True, False, False]]) # boolean 인덱싱은 로우에 적용된다.
print(fruit_df.loc[[False, True, True, False, False]])
print(fruit_df.iloc[[False, True, True, False, False]])

fresh     False
rotten     True
모든과일       True
Name: 바나나, dtype: bool
<class 'pandas.core.series.Series'>
     fresh  rotten  모든과일
사과     846     232  1078
배      343     123   466
바나나     17      45    62
딸기    2954       2  2956
오렌지    440      30   470
--------
     fresh  rotten  모든과일
배      343     123   466
바나나     17      45    62
     fresh  rotten  모든과일
배      343     123   466
바나나     17      45    62
     fresh  rotten  모든과일
배      343     123   466
바나나     17      45    62


df column indexing []
1. 문자열 (열 이름): df['column_name'] -> 해당 이름의 열 선택 (Series)
2. 문자열 리스트(열 이름 리스트): df['col1', 'col2'] -> 해당 이름의 열들 선택 (DataFrame)
3. 슬라이싱 (레이블 또는 위치): df['start':'end'], df[0:5] -> 해당 범위의 행 선택 (DataFrame)
4. 불리언 리스트/Series: df[불리언 리스트] -> True에 해당하는 행 선택 (DataFrame)

In [ ]:
#더하기
s= pd.Series(np.random.randint(0, 10, 5))
print(s)
print(np.exp(s))

0    1
1    9
2    8
3    2
4    9
dtype: int64
0       2.718282
1    8103.083928
2    2980.957987
3       7.389056
4    8103.083928
dtype: float64


In [ ]:
df = pd.DataFrame(np.random.randint(0, 10, (3, 3)), columns=['a', 'b', 'c'])
print(df)
print()
print(np.cos(df * np.pi))

   a  b  c
0  1  7  9
1  2  2  0
2  4  3  7

     a    b    c
0 -1.0 -1.0 -1.0
1  1.0  1.0  1.0
2  1.0 -1.0 -1.0


In [ ]:
s1 = pd.Series([1, 2, 3, 4, 5], index=[0, 1, 2, 3, 4])
s2 = pd.Series([5, 6, 7, 8, 9], index=[1, 2, 3, 4, 5])
print(s1+s2)
print()
print(s1.add(s2, fill_value=0)) # 없는 인덱스는 0으로 값을 채워서 연산

0     NaN
1     7.0
2     9.0
3    11.0
4    13.0
5     NaN
dtype: float64

0     1.0
1     7.0
2     9.0
3    11.0
4    13.0
5     9.0
dtype: float64


In [ ]:
df1 = pd.DataFrame(np.random.randint(0, 10, (3, 3)), columns=list('abc'))
df1

a  b  c
0  9  9  2
1  8  6  2
2  6  4  9

In [ ]:
df2 = pd.DataFrame(np.random.randint(0, 10, (5, 5)), columns=list('bcdef'))
df2

b  c  d  e  f
0  2  1  5  3  7
1  8  8  5  7  1
2  7  8  1  5  0
3  2  4  9  9  7
4  4  9  3  0  5

In [ ]:
print(df1 + df2)
print()
print(df1.add(df2))
print()

    a     b     c   d   e   f
0 NaN  11.0   3.0 NaN NaN NaN
1 NaN  14.0  10.0 NaN NaN NaN
2 NaN  11.0  17.0 NaN NaN NaN
3 NaN   NaN   NaN NaN NaN NaN
4 NaN   NaN   NaN NaN NaN NaN

    a     b     c   d   e   f
0 NaN  11.0   3.0 NaN NaN NaN
1 NaN  14.0  10.0 NaN NaN NaN
2 NaN  11.0  17.0 NaN NaN NaN
3 NaN   NaN   NaN NaN NaN NaN
4 NaN   NaN   NaN NaN NaN NaN



In [ ]:
print(df1.add(df2, fill_value=0))
print()

print(df1.add(df2, fill_value=1))
print()

#양쪽이 없는 경우는 NaN

     a     b     c    d    e    f
0  9.0  11.0   3.0  5.0  3.0  7.0
1  8.0  14.0  10.0  5.0  7.0  1.0
2  6.0  11.0  17.0  1.0  5.0  0.0
3  NaN   2.0   4.0  9.0  9.0  7.0
4  NaN   4.0   9.0  3.0  0.0  5.0

      a     b     c     d     e    f
0  10.0  11.0   3.0   6.0   4.0  8.0
1   9.0  14.0  10.0   6.0   8.0  2.0
2   7.0  11.0  17.0   2.0   6.0  1.0
3   NaN   3.0   5.0  10.0  10.0  8.0
4   NaN   5.0  10.0   4.0   1.0  6.0



In [ ]:
print(df1)
print(df2)
print()
print(df2-df1)
s1 = pd.Series([9, 9, 9], index= ['b', 'c', 'd'])
print(s1)
print(df1.sub(s1))

   a  b  c
0  9  9  2
1  8  6  2
2  6  4  9
   b  c  d  e  f
0  2  1  5  3  7
1  8  8  5  7  1
2  7  8  1  5  0
3  2  4  9  9  7
4  4  9  3  0  5

    a    b    c   d   e   f
0 NaN -7.0 -1.0 NaN NaN NaN
1 NaN  2.0  6.0 NaN NaN NaN
2 NaN  3.0 -1.0 NaN NaN NaN
3 NaN  NaN  NaN NaN NaN NaN
4 NaN  NaN  NaN NaN NaN NaN
b    9
c    9
d    9
dtype: int64
    a    b    c   d
0 NaN  0.0 -7.0 NaN
1 NaN -3.0 -7.0 NaN
2 NaN -5.0  0.0 NaN


In [ ]:
print(df1)
print()
print(df2-df1)
s2 = pd.Series([9, 9, 9], index= [1, 2, 3])
print(s2)
print(df1.sub(s2, axis=0)) # series index를 컬럼 인덱스와 정렬해서 연산 들어감 (디폴트 1)

   a  b  c
0  9  9  2
1  8  6  2
2  6  4  9

    a    b    c   d   e   f
0 NaN -7.0 -1.0 NaN NaN NaN
1 NaN  2.0  6.0 NaN NaN NaN
2 NaN  3.0 -1.0 NaN NaN NaN
3 NaN  NaN  NaN NaN NaN NaN
4 NaN  NaN  NaN NaN NaN NaN
1    9
2    9
3    9
dtype: int64
     a    b    c
0  NaN  NaN  NaN
1 -1.0 -3.0 -7.0
2 -3.0 -5.0  0.0
3  NaN  NaN  NaN


In [ ]:
print(df1)
print()
print(df1.iloc[1])
print()
print(df1.sub(df1.iloc[1]))
print()
print(df1['b'])
print()
print(df1.sub(df1['b']))
print(df1.sub(df1['b'], axis = 0))

   a  b  c
0  9  9  2
1  8  6  2
2  6  4  9

a    8
b    6
c    2
Name: 1, dtype: int64

   a  b  c
0  1  3  0
1  0  0  0
2 -2 -2  7

0    9
1    6
2    4
Name: b, dtype: int64

    a   b   c   0   1   2
0 NaN NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN NaN
   a  b  c
0  0  0 -7
1  2  0 -4
2  2  0  5


In [ ]:
print(df1 * df1.iloc[0])
print(df1.mul(df1.iloc[0]))
print(df1.multiply(df1.iloc[0]))
print(df1 * df1['a'])

    a   b   c
0  81  81   4
1  72  54   4
2  54  36  18
    a   b   c
0  81  81   4
1  72  54   4
2  54  36  18
    a   b   c
0  81  81   4
1  72  54   4
2  54  36  18
    a   b   c   0   1   2
0 NaN NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN NaN


In [ ]:
print (df1 / df1.iloc[2])
print (df1.truediv(df1.iloc[2]))
print (df1.div(df1.iloc[2]))
print (df1.divide(df1.iloc[2]))
print ()
print (df1 // df1.iloc[2])
print (df1.floordiv(df1.iloc[2]))

          a     b         c
0  1.500000  2.25  0.222222
1  1.333333  1.50  0.222222
2  1.000000  1.00  1.000000
          a     b         c
0  1.500000  2.25  0.222222
1  1.333333  1.50  0.222222
2  1.000000  1.00  1.000000
          a     b         c
0  1.500000  2.25  0.222222
1  1.333333  1.50  0.222222
2  1.000000  1.00  1.000000
          a     b         c
0  1.500000  2.25  0.222222
1  1.333333  1.50  0.222222
2  1.000000  1.00  1.000000

   a  b  c
0  1  2  0
1  1  1  0
2  1  1  1
   a  b  c
0  1  2  0
1  1  1  0
2  1  1  1


In [ ]:
print (df1 % df1.iloc[2])
print (df1.mod(df1.iloc[2]))
print ()
print (df1.pow(df1.iloc[0]))
print (df1**df1.iloc[0])

   a  b  c
0  3  1  2
1  2  2  2
2  0  0  0
   a  b  c
0  3  1  2
1  2  2  2
2  0  0  0

           a          b   c
0  387420489  387420489   4
1  134217728   10077696   4
2   10077696     262144  81
           a          b   c
0  387420489  387420489   4
1  134217728   10077696   4
2   10077696     262144  81


In [ ]:
s = pd.Series([4, 2, 6, 3, 1], index = ['a', 'c', 'b', 'e', 'd'])
print (s)
print ()
print (s.sort_index())
print (s.sort_values())

a    4
c    2
b    6
e    3
d    1
dtype: int64

a    4
b    6
c    2
d    1
e    3
dtype: int64
d    1
c    2
e    3
a    4
b    6
dtype: int64


정렬

In [ ]:
df = pd.DataFrame(np.random.randint(0, 10, (4, 4)),
                  index = [3, 5, 2, 4],
                  columns = list('bcda'))

print (df)
print ()
print (df.sort_index())        # row index 정렬, axis = 0이 default
print (df.sort_index(axis = 1)) # column index 정렬
print ()
print (df.sort_values(by = 'b'))
print ()
print (df.sort_values(by = ['b', 'c'])) #b 인덱스의 값이 같을 경우 c 인덱스로 정렬

   b  c  d  a
3  3  4  3  0
5  4  3  9  9
2  4  6  9  8
4  7  5  5  3

   b  c  d  a
2  4  6  9  8
3  3  4  3  0
4  7  5  5  3
5  4  3  9  9
   a  b  c  d
3  0  3  4  3
5  9  4  3  9
2  8  4  6  9
4  3  7  5  5

   b  c  d  a
3  3  4  3  0
5  4  3  9  9
2  4  6  9  8
4  7  5  5  3

   b  c  d  a
3  3  4  3  0
5  4  3  9  9
2  4  6  9  8
4  7  5  5  3


In [ ]:
s1 = pd.Series(['a', 'b'], index = [1, 2])
s2 = pd.Series(['c', 'd'], index = [2, 3])
s3 = pd.Series(['c', 'd'], index = [3, 4])

print (pd.concat([s1, s2])) #pandas는 인덱스 중복을 허용함
#pd.concat([s1, s2], verify_integrity = True) #중복이 있으면 에러 발생시킨다.
#보통 데이터를 합칠 때 오버랩이 되면 안되는 경우가 많다. 요걸 체크함
print (pd.concat([s1, s3], verify_integrity = True)) #중복이 없으므로 에러가 없음

1    a
2    b
2    c
3    d
dtype: object
1    a
2    b
3    c
4    d
dtype: object


Concat

In [ ]:
df1 = pd.DataFrame({'a':[14, 55], 'b':[64, 21]}, index = [0, 1])
df2 = pd.DataFrame({'a':[45, 83], 'b':[12, 76]}, index = [0, 1])
df3 = pd.DataFrame({'c':[64, 43], 'd':[67, 96]}, index = [0, 1])
df4 = pd.DataFrame({'c':[61, 12], 'd':[94, 34]}, index = [2, 3])
df5 = pd.DataFrame({'c':[14, 74], 'd':[27, 61]}, index = [10, 34])
df6 = pd.DataFrame({'a':[45, 33], 'b':[24, 53]}, index = [2, 3])

print (df1);print ()
print (df2);print ()
print (df3);print ()
print (df4);print ()
print (df5);print ()
print (df6);print ()

    a   b
0  14  64
1  55  21

    a   b
0  45  12
1  83  76

    c   d
0  64  67
1  43  96

    c   d
2  61  94
3  12  34

     c   d
10  14  27
34  74  61

    a   b
2  45  24
3  33  53



In [ ]:
# 기본 axis = 0, row행으로 붙인다.
print (pd.concat([df1, df2])) # column이 같고, index가 같은 경우
print (pd.concat([df1, df3])) # column이 다르고, index가 같은 경우
print ('-----------')
print (pd.concat([df1, df4], verify_integrity = True)) # 오버랩 없음
print ()
print (pd.concat([df1, df3])) # 오버랩 되도 그대로 붙인다.

    a   b
0  14  64
1  55  21
0  45  12
1  83  76
      a     b     c     d
0  14.0  64.0   NaN   NaN
1  55.0  21.0   NaN   NaN
0   NaN   NaN  64.0  67.0
1   NaN   NaN  43.0  96.0
-----------
      a     b     c     d
0  14.0  64.0   NaN   NaN
1  55.0  21.0   NaN   NaN
2   NaN   NaN  61.0  94.0
3   NaN   NaN  12.0  34.0

      a     b     c     d
0  14.0  64.0   NaN   NaN
1  55.0  21.0   NaN   NaN
0   NaN   NaN  64.0  67.0
1   NaN   NaN  43.0  96.0


In [ ]:
#print (pd.concat([df1, df3], verify_integrity = True)) # index 오버랩 있으면 에러
print (pd.concat([df1, df6], verify_integrity = True)) # column 오버랩은 신경안쓴다.
print ()
print (pd.concat([df1, df3], ignore_index = True)) # 오버랩 있든 말든 무시하고 새로운 index 생성
print (pd.concat([df1, df5], ignore_index = True)) # 오버랩 있든 말든

    a   b
0  14  64
1  55  21
2  45  24
3  33  53

      a     b     c     d
0  14.0  64.0   NaN   NaN
1  55.0  21.0   NaN   NaN
2   NaN   NaN  64.0  67.0
3   NaN   NaN  43.0  96.0
      a     b     c     d
0  14.0  64.0   NaN   NaN
1  55.0  21.0   NaN   NaN
2   NaN   NaN  14.0  27.0
3   NaN   NaN  74.0  61.0


Merge

In [ ]:
df1 = pd.DataFrame({'직원': ['성시경', '유재석', '김종국', '송지효'],
                    '부서': ['영업부', '개발부', '선도부', '정보부']})
df2 = pd.DataFrame({'직원': ['성시경', '유재석', '김종국', '송지효'],
                    '입사년도': [2020, 2018, 2021, 2022]})

print(df1); print()
print(df2); print()
print(pd.merge(df1, df2))

    직원   부서
0  성시경  영업부
1  유재석  개발부
2  김종국  선도부
3  송지효  정보부

    직원  입사년도
0  성시경  2020
1  유재석  2018
2  김종국  2021
3  송지효  2022

    직원   부서  입사년도
0  성시경  영업부  2020
1  유재석  개발부  2018
2  김종국  선도부  2021
3  송지효  정보부  2022


문자열

In [ ]:
names = ['길동 홍', '스티브 우', '순신 이', '줄리엔 강', '나일론 머스크']
names_s = pd.Series(names)
print(names_s); print()

print(names_s.str.len())  # 파이썬과 유사한 많은 함수를 제공
print()

print(names_s.str.split())
print(names_s.str[:3])
print(names_s.str.split().str.get(-1))  # 뒷 str만 얻기

0       길동 홍
1      스티브 우
2       순신 이
3      줄리엔 강
4    나일론 머스크
dtype: object

0    4
1    5
2    4
3    5
4    7
dtype: int64

0       [길동, 홍]
1      [스티브, 우]
2       [순신, 이]
3      [줄리엔, 강]
4    [나일론, 머스크]
dtype: object
0    길동 
1    스티브
2    순신 
3    줄리엔
4    나일론
dtype: object
0      홍
1      우
2      이
3      강
4    머스크
dtype: object


None, NaN

In [ ]:
n0 = np.array([0, 1, 2])
n00 = np.array([0, 1, 2.0])
n1 = np.array([0, 1, 2, None, 4, 5])
n2 = np.array([0, 1, 2, np.nan, 4, 5])
print(n0.dtype)
print(n00.dtype)
print(n1.dtype)
print(n2.dtype)  # nan은 float 취급
print(0 + np.nan)
print(np.nan + np.nan)
# print(np.sum(n1))  # None은 숫자가 아니므로 에러를 뽑는다. nan의 존재 이유
print(np.sum(n2))  #
print(np.nansum(n2))  # nan을 0.0으로 취급하여 합산 ***********************

int64
float64
object
float64
nan
nan
nan
12.0


In [ ]:
# series는 저장에 가장 적절한 데이터 타입으로 자동으로 결정된다.
print(pd.Series([1, 2, None, np.nan]))  # pandas에서 None은 언제 nan이 되는가?
print()
print(pd.Series([None, np.nan]))       # dtype에 주목
print()
print(pd.Series([True, None, np.nan])) # boolean은 object
print()
print(pd.Series(['a', None, np.nan]))  # str은 object
# none을 제외한 원소들로 dtype이 결정되며, none은 이에 따라 nan이 되거나 그대로 있다.

0    1.0
1    2.0
2    NaN
3    NaN
dtype: float64

0   NaN
1   NaN
dtype: float64

0    True
1    None
2     NaN
dtype: object

0       a
1    None
2     NaN
dtype: object


In [ ]:
s1 = pd.Series([1, 2, 'abcd', True, None, np.nan])
print(s1); print()

print(s1.isnull())
print(s1.notnull()); print()
print(s1[s1.notnull()])  # boolean indexing
print()

print(s1.dropna()); print()
print(s1.fillna(0))

0       1
1       2
2    abcd
3    True
4    None
5     NaN
dtype: object

0    False
1    False
2    False
3    False
4     True
5     True
dtype: bool
0     True
1     True
2     True
3     True
4    False
5    False
dtype: bool

0       1
1       2
2    abcd
3    True
dtype: object

0       1
1       2
2    abcd
3    True
dtype: object

0       1
1       2
2    abcd
3    True
4       0
5       0
dtype: object


In [ ]:
df = pd.DataFrame({'first': ['a', 'b', 'c'] * 3,
                   'second': [1, 2, 1, 1, 2, 3, 3, 4, 2]})  # list repetition

print(df); print()

print(df.duplicated())  # 중복 여부
print(df.drop_duplicates())  # 중복 제거 3, 4 index 삭제

  first  second
0     a       1
1     b       2
2     c       1
3     a       1
4     b       2
5     c       3
6     a       3
7     b       4
8     c       2

0    False
1    False
2    False
3     True
4     True
5    False
6    False
7    False
8    False
dtype: bool
  first  second
0     a       1
1     b       2
2     c       1
5     c       3
6     a       3
7     b       4
8     c       2


In [ ]:
s = pd.Series([1, 2, 3, -9999, 4, -10001])
print(s); print()

print(s.replace(s[3], np.nan)); print()
print(s.replace([s[3], s[5]], np.nan)); print()
print(s.replace([-9999, -10001], np.nan)); print()

0        1
1        2
2        3
3    -9999
4        4
5   -10001
dtype: int64

0        1.0
1        2.0
2        3.0
3        NaN
4        4.0
5   -10001.0
dtype: float64

0    1.0
1    2.0
2    3.0
3    NaN
4    4.0
5    NaN
dtype: float64

0    1.0
1    2.0
2    3.0
3    NaN
4    4.0
5    NaN
dtype: float64



In [ ]:
print(s.replace([s[s < -1000]], np.nan)); print()  # series는 여러 원소라는 개념이므로 리스트 안에 넣는다.
print(s[s < -1000]); print()
print(s[s < -1000]); print()

0    1.0
1    2.0
2    3.0
3    NaN
4    4.0
5    NaN
dtype: float64

3    -9999
5   -10001
dtype: int64

3    -9999
5   -10001
dtype: int64

